% simple script to open a WAV file generated by E310 containing I/Q samples
% and then demodulating this file assuming FM modulation
% run this on the E310
% ./rx_samples_to_file --rate 640000 --freq 107300000 --type double --duration 10 --gain 40 --file e310data1.dat

fid = fopen('usrp_samples.dat','rb');
tmp = fread(fid,'float');
samples = zeros(length(tmp)/2,2);
samples(:,1) = tmp(1:2:end);
samples(:,2) = tmp(2:2:end);
%fs = 640000;

